server:
  port: 8888

spring:
  application:
    name: begin-service

  profiles:
   active:
    - dev

jetcache:
  statIntervalMinutes: 15
  areaInCacheName: false
  local:
    default:
      type: linkedhashmap
      keyConvertor: fastjson
  remote:
    default:
      type: redis
      keyConvertor: fastjson
      valueEncoder: java
      valueDecoder: java
      poolConfig:
        minIdle: 5
        maxIdle: 20
        maxTotal: 50
      host: 127.0.0.1
      port: 6379



---
spring:
  profiles: dev

  datasource:
    url: jdbc:oracle:thin:@10.102.0.240:1521:orcl
    username: LYTEST
    password: LYTEST
    driver-class-name: oracle.jdbc.OracleDriver
    type: com.alibaba.druid.pool.DruidDataSource